"""Supplemental source-form fields. Main outcomes are typed model columns."""
# field name, display label, kind, choices. None means free entry.
PATIENT_FIELDS = [
 ('marital_status','Marital status','choice',['Single','Married','Divorced/Separated','Widowed']),
 ('residence','Residence','choice',['Urban','Rural']),('country','Country','text',None),('state','State / region','text',None),
 ('occupation','Occupation','text',None),('employment','Employment','choice',['Employed','Unemployed','Student','Retired']),
 ('education','Education','choice',['None','Primary','Secondary','Tertiary']),('insurance','Insurance','choice',['Yes','No','Unknown']),
 ('referral','Referral source','choice',['Self','Primary facility','Secondary','Tertiary','Other']),
 ('smoking','Smoking status','choice',['Never','Former','Current']),('pack_years','Pack-years','number',None),
 ('alcohol','Alcohol use','choice',['Never','Former','Current']),('alcohol_units_week','Alcohol units per week (record local unit definition in notes)','number',None),
 ('recreational_drugs','Recreational drug use','long',None),('physical_activity','Physical activity','choice',['Low','Moderate','High']),
 ('exercise','Regular exercise','choice',['Yes','No','Unknown']),('heavy_lifting','Heavy lifting','choice',['Yes','No','Unknown']),
 ('prolonged_sitting','Prolonged sitting / driving','choice',['Yes','No','Unknown']),('weight_kg','Weight (kg)','number',None),('height_cm','Height (cm)','number',None),
 ('comorbidities_present','Comorbidities present','choice',['Yes','No','Unknown']),
 ('previous_surgery_present','Previous spinal surgery present','choice',['Yes','No','Unknown']),
 ('comorbidities','Comorbidities: diagnosis, duration and current treatment','long',None),('symptoms','Symptoms and durations','long',None),
 ('primary_symptom','Primary symptom','text',None),('symptom_duration','Primary symptom duration category','choice',['Acute <3 weeks','Subacute 3–6 weeks','Chronic >6 weeks']),
 ('previous_surgery','Previous spinal surgery: procedures and dates','long',None),('examination','Key examination findings','long',None),
 ('neurological_deficit','Neurological deficit present','choice',['Yes','No','Unknown']),('deficit_description','Neurological deficit details','long',None),
 ('xray','X-ray findings','long',None),('mri','MRI findings','long',None),('ct','CT findings','long',None),('labs','Laboratory results (include units)','long',None),
 ('other_investigations','Other investigations','long',None),('comments','Additional observations (avoid direct identifiers)','long',None)]
PROCEDURE_FIELDS=[('intraoperative_complications','Intraoperative complications reported (add an event for each Yes)','choice',['Yes','No','Unknown']),('anaesthetic_complications','Anaesthetic complications reported (add an event for each Yes)','choice',['Yes','No','Unknown']),('indication','Indication for surgery','long',None),('frailty_index','Frailty index value and instrument','text',None),('charlson_index','Charlson comorbidity index','number',None),('anaesthetic_considerations','Special anaesthetic considerations / difficulties','long',None),('neuromonitoring','Neuromonitoring','choice',['Yes','No','Unknown']),('transfusion','Transfusion','choice',['Yes','No','Unknown'])]
ASSESSMENT_FIELDS=[('postoperative_complications','Postoperative complications reported (add an event for each Yes)','choice',['Yes','No','Unknown']),('symptom_recurrence','Symptoms recurred (add an event for each Yes)','choice',['Yes','No','Unknown']),('walking_change','Walking improvement: comments','long',None),('return_activities','Return to normal activities','text',None),('symptom_improvement','Improvement in symptoms','long',None),('surgery_satisfaction','Satisfaction with surgery: comments','long',None),('recommendation','Would recommend procedure','choice',['Yes','No','Unsure']),('satisfaction','Overall satisfaction','choice',['Very satisfied','Satisfied','Neutral','Dissatisfied','Very dissatisfied']),('macnab','Patient perceived outcome / Macnab category','choice',['Excellent','Good','Fair','Poor']),('global_change','Global impression of change','choice',['Much worse','Worse','No change','Improved','Much improved']),('spinopelvic_notes','Spinopelvic parameters: other measurements and method','long',None),('pi','Pelvic incidence (degrees)','signed',None),('pt','Pelvic tilt (degrees)','signed',None),('ss','Sacral slope (degrees)','signed',None),('ll','Lumbar lordosis (degrees)','signed',None),('sva','Sagittal vertical axis (mm)','signed',None),('cobb','Cobb angle (degrees)','signed',None),('comments','Visit comments (avoid direct identifiers)','long',None)]
