# Generated by Django 5.2.18 on 2026-10-08 07:30

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_id', models.CharField(max_length=40, unique=True, verbose_name='Research number / study ID')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Unknown', 'Unknown')], max_length=16, verbose_name='Biological sex')),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(120)], verbose_name='Age at enrolment (years)')),
                ('enrolled_on', models.DateField(default=django.utils.timezone.localdate)),
                ('diagnosis', models.CharField(blank=True, max_length=200)),
                ('synthetic', models.BooleanField(default=True, editable=False)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('view_identity', 'View restricted identifiers'), ('change_identity', 'Change restricted identifiers'), ('export_research', 'Export research records'), ('view_audit', 'View audit trail')],
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('entity', models.CharField(max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=60)),
                ('changed_fields', models.JSONField(default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_number', models.CharField(blank=True, max_length=100)),
                ('initials', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identity', to='registry.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Surgery date')),
                ('approach', models.CharField(choices=[('Endoscopic', 'Endoscopic'), ('Open', 'Open')], max_length=30)),
                ('endoscopic_type', models.CharField(blank=True, choices=[('Uniportal', 'Uniportal'), ('Biportal', 'Biportal')], max_length=30)),
                ('operation', models.CharField(max_length=200, verbose_name='Specific operation')),
                ('levels', models.CharField(max_length=200, verbose_name='Operated levels (comma-separated)')),
                ('instrumented', models.BooleanField(default=False)),
                ('duration_hours', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Surgery duration (hours)')),
                ('blood_loss_ml', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estimated blood loss (mL)')),
                ('anaesthesia', models.CharField(choices=[('Local', 'Local'), ('Regional', 'Regional'), ('General', 'General'), ('Combined', 'Combined'), ('Other', 'Other')], max_length=30)),
                ('asa', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='ASA grade')),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('hospital_days', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Hospital stay (days)')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedures', to='registry.patient')),
            ],
            options={
                'ordering': ['date', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('kind', models.CharField(choices=[('Intraoperative complication', 'Intraoperative complication'), ('Postoperative complication', 'Postoperative complication'), ('Anaesthetic complication', 'Anaesthetic complication'), ('Reoperation', 'Reoperation'), ('Symptom recurrence', 'Symptom recurrence')], max_length=30)),
                ('description', models.CharField(max_length=250)),
                ('severity', models.CharField(blank=True, max_length=40)),
                ('management', models.TextField(blank=True)),
                ('reoperation_procedure', models.CharField(blank=True, max_length=200)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='registry.patient')),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='registry.procedure')),
            ],
            options={
                'ordering': ['date', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment', models.CharField(max_length=200, verbose_name='Non-operative treatment')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('ongoing', models.BooleanField(default=False)),
                ('outcome', models.TextField(blank=True)),
                ('steroid_injection', models.BooleanField(default=False)),
                ('injection_frequency', models.CharField(blank=True, max_length=100)),
                ('injection_outcome', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatments', to='registry.patient')),
            ],
            options={
                'ordering': ['start_date', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Assessment date')),
                ('timepoint', models.CharField(choices=[('baseline', 'Baseline'), ('postop', 'Immediate postoperative'), ('3m', '3 months'), ('6m', '6 months'), ('9m', '9 months'), ('1y', '1 year'), ('2y', '2 years'), ('unscheduled', 'Unscheduled')], max_length=20)),
                ('vas_main', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='VAS main complaint (0–10)')),
                ('pain_site', models.CharField(blank=True, choices=[('Back', 'Back'), ('Neck', 'Neck'), ('Other', 'Other')], max_length=10)),
                ('vas_worst_radicular', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='VAS worst radicular limb (0–10)')),
                ('vas_other_radicular', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='VAS other radicular limb (0–10)')),
                ('worst_limb', models.CharField(blank=True, choices=[('Left arm', 'Left arm'), ('Right arm', 'Right arm'), ('Left leg', 'Left leg'), ('Right leg', 'Right leg'), ('None', 'None')], max_length=20, verbose_name='Worst radicular limb at this visit')),
                ('odi', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='ODI (0–100)')),
                ('ndi', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='NDI normalised score (0–100)')),
                ('walking_m', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Walking distance (metres)')),
                ('walking_definition', models.CharField(blank=True, max_length=200, verbose_name='Walking measurement definition / protocol')),
                ('sf_physical_functioning', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='SF-36 physical functioning (0–100)')),
                ('sf_role_physical', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='SF-36 role physical (0–100)')),
                ('sf_bodily_pain', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='SF-36 bodily pain (0–100)')),
                ('sf_general_health', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='SF-36 general health (0–100)')),
                ('sf_vitality', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='SF-36 vitality (0–100)')),
                ('sf_social_functioning', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='SF-36 social functioning (0–100)')),
                ('sf_role_emotional', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='SF-36 role emotional (0–100)')),
                ('sf_mental_health', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='SF-36 mental health (0–100)')),
                ('sf_pcs', models.FloatField(blank=True, null=True, verbose_name='SF-36 PCS')),
                ('sf_mcs', models.FloatField(blank=True, null=True, verbose_name='SF-36 MCS')),
                ('sf_version', models.CharField(blank=True, max_length=100, verbose_name='SF-36 instrument version')),
                ('sf_scoring_method', models.CharField(blank=True, max_length=250, verbose_name='SF-36 component scoring method / reference norms')),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Missed', 'Missed'), ('Declined', 'Declined'), ('Not due', 'Not due')], default='Completed', max_length=20, verbose_name='Visit status')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='registry.patient')),
                ('procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='registry.procedure')),
            ],
            options={
                'ordering': ['date', 'pk'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('procedure__isnull', False), models.Q(('timepoint', 'unscheduled'), _negated=True)), fields=('patient', 'procedure', 'timepoint'), name='unique_procedure_visit')],
            },
        ),
    ]
