# Generated by Django 5.2.18 on 2026-10-08 07:31

import django.core.validators
import registry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='ndi',
            field=models.FloatField(blank=True, null=True, validators=[registry.models.finite, django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='NDI normalised score (0–100)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='odi',
            field=models.FloatField(blank=True, null=True, validators=[registry.models.finite, django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='ODI (0–100)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='sf_bodily_pain',
            field=models.FloatField(blank=True, null=True, validators=[registry.models.finite, django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='SF-36 bodily pain (0–100)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='sf_general_health',
            field=models.FloatField(blank=True, null=True, validators=[registry.models.finite, django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='SF-36 general health (0–100)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='sf_mcs',
            field=models.FloatField(blank=True, null=True, validators=[registry.models.finite], verbose_name='SF-36 MCS'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='sf_mental_health',
            field=models.FloatField(blank=True, null=True, validators=[registry.models.finite, django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='SF-36 mental health (0–100)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='sf_pcs',
            field=models.FloatField(blank=True, null=True, validators=[registry.models.finite], verbose_name='SF-36 PCS'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='sf_physical_functioning',
            field=models.FloatField(blank=True, null=True, validators=[registry.models.finite, django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='SF-36 physical functioning (0–100)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='sf_role_emotional',
            field=models.FloatField(blank=True, null=True, validators=[registry.models.finite, django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='SF-36 role emotional (0–100)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='sf_role_physical',
            field=models.FloatField(blank=True, null=True, validators=[registry.models.finite, django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='SF-36 role physical (0–100)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='sf_social_functioning',
            field=models.FloatField(blank=True, null=True, validators=[registry.models.finite, django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='SF-36 social functioning (0–100)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='sf_vitality',
            field=models.FloatField(blank=True, null=True, validators=[registry.models.finite, django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='SF-36 vitality (0–100)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='vas_main',
            field=models.FloatField(blank=True, null=True, validators=[registry.models.finite, django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='VAS main complaint (0–10)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='vas_other_radicular',
            field=models.FloatField(blank=True, null=True, validators=[registry.models.finite, django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='VAS other radicular limb (0–10)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='vas_worst_radicular',
            field=models.FloatField(blank=True, null=True, validators=[registry.models.finite, django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='VAS worst radicular limb (0–10)'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='walking_m',
            field=models.FloatField(blank=True, null=True, validators=[registry.models.finite, django.core.validators.MinValueValidator(0)], verbose_name='Walking distance (metres)'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='blood_loss_ml',
            field=models.FloatField(blank=True, null=True, validators=[registry.models.finite, django.core.validators.MinValueValidator(0)], verbose_name='Estimated blood loss (mL)'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='duration_hours',
            field=models.FloatField(blank=True, null=True, validators=[registry.models.finite, django.core.validators.MinValueValidator(0)], verbose_name='Surgery duration (hours)'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='hospital_days',
            field=models.FloatField(blank=True, null=True, validators=[registry.models.finite, django.core.validators.MinValueValidator(0)], verbose_name='Hospital stay (days)'),
        ),
    ]
